services:
    frontend:
        build:
            context: ./mintflow
            dockerfile: Dockerfile
        ports:
            - "5173:5173"
        volumes:
            - ./mintflow:/app
            - /app/node_modules
        environment:
            - CHOKIDAR_USEPOLLING=true
        depends_on:
            - backend

    backend:
        build:
            context: ./mintflow-backend
            dockerfile: Dockerfile
        ports:
            - "8081:8081"

        environment:
            - MONGO_URI=mongodb://db:27017/mintflow-db

        volumes:
            - ./mintflow-backend:/app
            - /app/node_modules
        depends_on:
            db:
                condition: service_healthy

    db:
        image: mongo:latest
        container_name: mintflow-db
        ports:
            - "27017:27017"
        volumes:
            - db:/data/db
            - ./db/:/docker-entrypoint-initdb.d
            - ./db/mongod.conf:/etc/mongod.conf
        command: ["--config", "/etc/mongod.conf"]
        healthcheck:
            test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
            interval: 10s
            timeout: 5s
            retries: 5

volumes:
    db:
